version: '3'

tasks:
  clean:
    cmds:
      - ./gradlew clean
  build:
    cmds:
      - task: clean
      - ./gradlew build
  run:
    cmds:
      - docker compose up --build -d
  restart:
    cmds:
      - docker compose down
      - docker compose up --build -d