name: Update files with commit

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Generate README.md
        uses: probablykasper/readme-template-action@v1
        with:
          token: ${{ secrets.JAVA_TOKEN }}
          template: TEMPLATE.md
          output: README.md
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: .
          message: 'update files'