name: publish-documentation

on:
  workflow_dispatch:

jobs:
  build-dokka:
    needs: [ bump-gradle-version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build html
        run: ./gradlew dokkaHtml --no-daemon --stacktrace
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kia-docs
          path: build/dokka/html
  deploy-dokka:
    runs-on: ubuntu-latest
    needs: [ build-dokka ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: kia-docs
          path: public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.JAVA_TOKEN }}
          keep_files: true
          publish_dir: ./public
          full_commit_message: Publish dokka