name: Deploy to github pages

on:
  push:
    branches:
      - master

jobs:
  build-dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build html
        run: ./gradlew dokkaHtml --no-daemon --stacktrace
        working-directory: ./kia
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kia
          path: gradle/kia/build/dokka
  deploy:
    runs-on: ubuntu-latest
    needs: [ build-dokka ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: kia
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.JAVA_TOKEN }}
          keep_files: true
          publish_dir: ./public
          full_commit_message: Publish dokka