name: Publish package to GitHub Packages and deploy dokka
on: push
jobs:
  bump-gradle-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Bump Version
        id: bump
        uses: IMGARENA/version-bump-action@v3
        with:
          github-token: ${{ secrets.JAVA_TOKEN }}
  publish:
    needs: [ bump-gradle-version ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
  build-dokka:
    needs: [ bump-gradle-version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build html
        run: ./gradlew dokkaHtml --no-daemon --stacktrace
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kia-docs
          path: build/dokka/html
  deploy-dokka:
    runs-on: ubuntu-latest
    needs: [ build-dokka ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: kia-docs
          path: public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.JAVA_TOKEN }}
          keep_files: true
          publish_dir: ./public
          full_commit_message: Publish dokka