name: Publish
on: push
jobs:
  bump-gradle-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
      old_version: ${{ steps.bump.outputs.initial-version }}
      commit_hash: ${{ steps.bump.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Bump Version
        id: bump
        uses: IMGARENA/version-bump-action@v3
        with:
          github-token: ${{ secrets.JAVA_TOKEN }}
      - name: Echo Version
        run: |
            echo "version=${{ steps.bump.outputs.version }}" >> "$GITHUB_OUTPUT"
            echo "old_version=${{ steps.bump.outputs.initial-version }}" >> "$GITHUB_OUTPUT"
  publish-package:
    needs: [ bump-gradle-version ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Replace gradle version
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'gradle.build'
          search-text: "version='${{needs.bump-gradle-version.outputs.old_version}}'"
          replacement-text: "version='${{needs.bump-gradle-version.outputs.version}}'"
          encoding: 'utf8'
          max-parallelism: 10
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
  build-dokka:
    needs: [ bump-gradle-version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build html
        run: ./gradlew dokkaHtml --no-daemon --stacktrace
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kia-docs
          path: build/dokka/html
  build-jar:
    needs: [ bump-gradle-version ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Build package
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kia-jar
          path: build/libs/*all.jar
  deploy-dokka:
    runs-on: ubuntu-latest
    needs: [ build-dokka ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: kia-docs
          path: public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.JAVA_TOKEN }}
          keep_files: true
          publish_dir: ./public
          full_commit_message: Publish dokka
  release:
    needs: [ build-jar, bump-gradle-version ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: kia-jar
          path: plugin/
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{needs.bump-gradle-version.outputs.version}}
          artifacts: "plugin/*.jar"
      - name: Trigger post release workflow
        env:
          GH_TOKEN: ${{ secrets.JAVA_TOKEN }}
        run: gh workflow run post-release.yml --ref ${{needs.bump-gradle-version.outputs.version}} -f old=${{needs.bump-gradle-version.outputs.old_version}}
